# Generated by Django 4.1 on 2022-09-10 13:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizinstance_quiz_remove_quizinstance_taker_and_more'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='completed_subject',
            field=models.ManyToManyField(default=django.db.models.manager.BaseManager.all, to='quiz.subject'),
        ),
    ]
