# Generated by Django 4.1 on 2022-09-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizinstance_quiz_remove_quizinstance_taker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizinstance',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
