# Generated by Django 4.1 on 2022-09-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizinstance_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizinstance',
            name='username',
        ),
        migrations.RemoveField(
            model_name='quizinstance',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizinstance',
            name='taker',
        ),
        migrations.AddField(
            model_name='quizinstance',
            name='quiz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quizinstance',
            name='taker',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
